<h1>contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# Notebook for testing Dataiku plugin functionality

In [65]:
!ls -l octave-workspace
!rm -rf octave-workspace
!rm -rf Detector.mat
!rm -rf Log.txt
import oct2py as op

-rw-r--r--  1 Bhill  staff  153 Mar  3 22:57 octave-workspace


In [66]:
o = op.Oct2Py()

In [67]:
octave = o

In [68]:
o.version()

'4.4.1'

In [69]:
o.restart()

In [70]:
o.eval('clear all')

In [71]:
o.addpath(o.genpath('octave'))

'.:/anaconda3/lib/python3.7/site-packages/oct2py:/anaconda3/lib/python3.7/site-packages/octave_kernel:/usr/local/Cellar/octave/4.4.1_5/share/octave/site/m:/usr/local/Cellar/octave/4.4.1_5/share/octave/site/m/startup:/usr/local/Cellar/octave/4.4.1_5/lib/octave/4.4.1/oct/x86_64-apple-darwin18.2.0:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/audio:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/deprecated:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/elfun:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/general:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/geometry:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/gui:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/help:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/image:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/io:/usr/local/Cellar/octave/4.4.1_5/share/octave/4.4.1/m/java:/usr/local/Cellar/octave/4.4.1_5/share/octave/4

In [72]:
o.eval("opts=acfTrain();")
o.eval("opts.posWinDir = 'images/simple/posWinDir/';")
o.eval("opts.negWinDir = 'images/simple/negWinDir/';")
o.eval("opts.modelDs = [19  19];")
o.eval("opts.modelDsPad = [20  20];")
o.eval("model = acfTrain(opts);")

---------------------------------------------------------------------------
Training stage 0
Done sampling windows (time=1s).
Computing lambdas... done (time=1s).
Extracting features... done (time=0s).
Done sampling windows (time=0s).
Extracting features... done (time=0s).
Training AdaBoost: nWeak=128 nFtrs=250 pos=88 neg=3
 i=  16 alpha=5.000 err=0.000 loss=1.80e-35
 stopping early
Done training err=0.0000 fp=0.0000 fn=0.0000 (t=0.1s).
Done training stage 0 (time=2s).
---------------------------------------------------------------------------
Done training (time=2s).


In [54]:
opts = o.acfTrain()

Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file

In [35]:
opts

"acfTrain" Octave function

In [37]:
octave.feval('opts')

Oct2PyError: Octave evaluation error:
error: feval: function 'opts' not found

In [27]:
ptr.address

'opts'

In [13]:
opts

NameError: name 'opts' is not defined

In [ ]:
octave.eval('x = struct("y", {1, 2}, "z", {3, 4});')
x = octave.pull('x')

In [5]:
 t = o.eval('rand(1, 2)', verbose=True)

ans =

   0.55027   0.71317



In [7]:
o.eval('foo = [1, 2];')

In [8]:
ptr = o.get_pointer('foo')

In [9]:
ptr.value

array([[1., 2.]])

In [33]:
o.eval('opts=acfTrain()', verbose=True)

opts =

  scalar structure containing the fields:

    pPyramid =

      scalar structure containing the fields:

        pChns =

          scalar structure containing the fields:

            shrink: 1x1 scalar
            pColor: 1x1 scalar struct
            pGradMag: 1x1 scalar struct
            pGradHist: 1x1 scalar struct
            pCustom: 0x0 struct
            complete: 1x1 scalar

        nPerOct =  8
        nOctUp = 0
        nApprox =  7
        lambdas = [](0x0)
        pad =

           16   12

        minDs =

           100    41

        smooth =  1
        concat =  1
        complete =  1

    filters = [](0x0)
    modelDs =

       100    41

    modelDsPad =

       128    64

    pNms =

      scalar structure containing the fields:

        type = maxg
        overlap =  0.65000
        ovrDnm = min

    stride =  4
    cascThr = -1
    cascCal =  0.0050000
    nWeak =  128
    pBoost =

      scalar structure containing the fields:

        pTree =

      

In [34]:
o.pull('opts')

Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file

In [30]:
opts

NameError: name 'opts' is not defined

In [8]:
op.demo()

>>> #########################
>>> # Oct2Py demo
>>> #########################
>>> import numpy as np
>>> from oct2py import Oct2Py
>>> oc = Oct2Py()
>>> # basic commands
>>> print(oc.abs(-1))
1
>>> print(oc.upper('xyz'))
XYZ
>>> # plotting
>>> oc.plot([1,2,3],'-o', linewidth=2)


/anaconda3/lib/python3.7/site-packages/oct2py/demo.py:1: UserWarning: Key - value pairs are deprecated, use `func_args`
  # -*- coding: utf-8 -*-


Press Enter to continue...
>>> oc.close()
>>> xx = np.arange(-2*np.pi, 2*np.pi, 0.2)
>>> oc.surf(np.subtract.outer(np.sin(xx), np.cos(xx)))
Press Enter to continue...
>>> oc.close()
>>> # getting help
>>> help(oc.svd)
Help on svd in module oct2py.dynamic object:

class svd(OctaveFunctionPtr)
 |  svd(session_weakref, name)
 |  
 |  'svd' is a built-in function from the file libinterp/corefcn/svd.cc
 |  
 |   -- S = svd (A)
 |   -- [U, S, V] = svd (A)
 |   -- [U, S, V] = svd (A, "econ")
 |   -- [U, S, V] = svd (A, 0)
 |       Compute the singular value decomposition of A.
 |  
 |       The singular value decomposition is defined by the relation
 |  
 |            A = U*S*V'
 |  
 |       The function 'svd' normally returns only the vector of singular
 |       values.  When called with three return values, it computes U, S,
 |       and V.  For example,
 |  
 |            svd (hilb (3))
 |  
 |       returns
 |  
 |            ans =
 |  
 |              1.4083189
 |              0.1223271