<h1>contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# Notebook for testing Dataiku plugin functionality

In [1]:
import oct2py as op

In [2]:
o = op.Oct2Py()

In [3]:
!rm -rf Detector.mat
!rm -rf Log.txt

In [8]:
op.demo()

>>> #########################
>>> # Oct2Py demo
>>> #########################
>>> import numpy as np
>>> from oct2py import Oct2Py
>>> oc = Oct2Py()
>>> # basic commands
>>> print(oc.abs(-1))
1
>>> print(oc.upper('xyz'))
XYZ
>>> # plotting
>>> oc.plot([1,2,3],'-o', linewidth=2)


/anaconda3/lib/python3.7/site-packages/oct2py/demo.py:1: UserWarning: Key - value pairs are deprecated, use `func_args`
  # -*- coding: utf-8 -*-


Press Enter to continue...
>>> oc.close()
>>> xx = np.arange(-2*np.pi, 2*np.pi, 0.2)
>>> oc.surf(np.subtract.outer(np.sin(xx), np.cos(xx)))
Press Enter to continue...
>>> oc.close()
>>> # getting help
>>> help(oc.svd)
Help on svd in module oct2py.dynamic object:

class svd(OctaveFunctionPtr)
 |  svd(session_weakref, name)
 |  
 |  'svd' is a built-in function from the file libinterp/corefcn/svd.cc
 |  
 |   -- S = svd (A)
 |   -- [U, S, V] = svd (A)
 |   -- [U, S, V] = svd (A, "econ")
 |   -- [U, S, V] = svd (A, 0)
 |       Compute the singular value decomposition of A.
 |  
 |       The singular value decomposition is defined by the relation
 |  
 |            A = U*S*V'
 |  
 |       The function 'svd' normally returns only the vector of singular
 |       values.  When called with three return values, it computes U, S,
 |       and V.  For example,
 |  
 |            svd (hilb (3))
 |  
 |       returns
 |  
 |            ans =
 |  
 |              1.4083189
 |              0.1223271

In [4]:
o.eval('clc')
o.eval('clear')
o.eval('addpath(genpath("octave"))')

In [5]:
 t = o.eval('rand(1, 2)', verbose=True)

ans =

   0.55027   0.71317



In [7]:
o.eval('foo = [1, 2];')

In [8]:
ptr = o.get_pointer('foo')

In [9]:
ptr.value

array([[1., 2.]])

In [33]:
o.eval('opts=acfTrain()', verbose=True)

opts =

  scalar structure containing the fields:

    pPyramid =

      scalar structure containing the fields:

        pChns =

          scalar structure containing the fields:

            shrink: 1x1 scalar
            pColor: 1x1 scalar struct
            pGradMag: 1x1 scalar struct
            pGradHist: 1x1 scalar struct
            pCustom: 0x0 struct
            complete: 1x1 scalar

        nPerOct =  8
        nOctUp = 0
        nApprox =  7
        lambdas = [](0x0)
        pad =

           16   12

        minDs =

           100    41

        smooth =  1
        concat =  1
        complete =  1

    filters = [](0x0)
    modelDs =

       100    41

    modelDsPad =

       128    64

    pNms =

      scalar structure containing the fields:

        type = maxg
        overlap =  0.65000
        ovrDnm = min

    stride =  4
    cascThr = -1
    cascCal =  0.0050000
    nWeak =  128
    pBoost =

      scalar structure containing the fields:

        pTree =

      

In [34]:
o.pull('opts')

Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file

In [30]:
opts

NameError: name 'opts' is not defined